### ISSUE TITLE
Docker サービスが起動していない状態で実行した際の、エラーメッセージが不適切

### ISSUE THREAD

**Issue by mikoto2000** [mikoto2000/devcontainer.vim#12]
以下のように、 `panic: unexpeted end of JSON input` というエラーが出る。
(Docker サービスが起動していないので、標準出力に JSON が出力されない状態のはず...)
 
```
[mikoto@letsarch devcontainer.vim]$ devcontainer.vim start .
Download vim from https://github.com/vim/vim-appimage/releases/download/v9.1.0346/Vim-v9.1.0346.glibc2.29-x86_64.AppImage ... done.
Download devcontainer from https://github.com/mikoto2000/devcontainers-cli/releases/download/v0.58.0-1/devcontainer-linux-x64-0.58.0-1 ... done.
run devcontainer: `/home/mikoto/.cache/devcontainer.vim/bin/devcontainer read-configuration --workspace-folder .`
panic: unexpected end of JSON input

goroutine 1 [running]:
main.main.func4(0xc0000c4800)
        github.com/mikoto2000/devcontainer.vim/main.go:214 +0x271
github.com/urfave/cli/v2.(*Command).Run(0xc00014c2c0, 0xc0000c4800, {0xc0000c8ba0, 0x2, 0x2})
        github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x97d
github.com/urfave/cli/v2.(*Command).Run(0xc00014c840, 0xc0000c4640, {0xc00009c0f0, 0x3, 0x3})
        github.com/urfave/cli/v2@v2.27.1/command.go:272 +0xbb7
github.com/urfave/cli/v2.(*App).RunContext(0xc0000c6200, {0x89d020, 0xb74ac0}, {0xc00009c0f0, 0x3, 0x3})
        github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x58b
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
        github.com/mikoto2000/devcontainer.vim/main.go:319 +0x8dc
```

**Comment by mikoto2000** [comment]
2079d07cc6a099e9eb61a3599ed71385d9411af7 で対応完了。
