### ISSUE TITLE
Linux で forwardPort を設定していると、初回以外起動に失敗する

### ISSUE THREAD

**Issue by mikoto2000** [mikoto2000/devcontainer.vim#78]
なんでぇ？？？？？？

**Comment by mikoto2000** [comment]
初回起動時に、`/pf` 下に設定ファイルが生成されないようだ。

**Comment by mikoto2000** [comment]
```
goroutine 11 [running]:
github.com/mikoto2000/devcontainer.vim/v3/devcontainer.Start.func2()
        github.com/mikoto2000/devcontainer.vim/v3/devcontainer/start.go:171 +0x5ff
created by github.com/mikoto2000/devcontainer.vim/v3/devcontainer.Start in goroutine 1
        github.com/mikoto2000/devcontainer.vim/v3/devcontainer/start.go:155 +0x1aec
mikoto@mikoto-CFRZ6-1L:~/project/OASIZ_TimeLogger2$ unable to setup input stream: unable to set IO streams as raw terminal: input/output error
```

**Comment by mikoto2000** [comment]
3710444192c2ccc9fc33aa845b9f50b02bda5281 で対応完了。
