### ISSUE TITLE
デフォルトユーザーが '/' に権限を持つユーザーでない場合に、 `/vim` の `chmod` に失敗する

### ISSUE THREAD

**Issue by mikoto2000** [mikoto2000/devcontainer.vim#9]
```sh
$ devcontainer.vim start .
vim aleady exist, use this.
devcontainer aleady exist, use this.
run devcontainer: `/home/mikoto/.cache/devcontainer.vim/bin/devcontainer read-configuration --workspace-folder .`
Use configuration file: `/home/mikoto/.cache/devcontainer.vim/config/5058f1af8388633f609cadb75a75dc9d/devcontainer.json`run container: `/home/mikoto/.cache/devcontainer.vim/bin/devcontainer "up" "--override-config" "/home/mikoto/.cache/devcontainer.vim/config/5058f1af8388633f609cadb75a75dc9d/devcontainer.json" "--workspace-folder" "."`
[2024-04-18T12:36:59.153Z] @devcontainers/cli 0.58.0. Node.js v21.7.2. linux 5.15.146.1-microsoft-standard-WSL2 x64.
finished devcontainer up: {success 3b345af413c3e7ac963428585bd3caa3dc05587c05657977e3bbb3a7acb8a28f  10001 /workspaces/quarkus-tutorial}
Copy AppImage: `docker "cp" "/home/mikoto/.cache/devcontainer.vim/bin/vim" "3b345af413c3e7ac963428585bd3caa3dc05587c05657977e3bbb3a7acb8a28f:/"` ... done.
Chown AppImage: `docker "exec" "3b345af413c3e7ac963428585bd3caa3dc05587c05657977e3bbb3a7acb8a28f" "sh" "-c" "chmod +x /vim"` ...chmod error.
chmod: changing permissions of '/vim': Operation not permitted

panic: exit status 1

goroutine 1 [running]:
github.com/mikoto2000/devcontainer.vim/devcontainer.ExecuteDevcontainer({0xc000029010, 0x1, 0x1}, {0xc000022540, 0x35}, {0xc00001e4e0, 0x2c}, {0xc0000a8180, 0x5e})
        github.com/mikoto2000/devcontainer.vim/devcontainer/devcontainer.go:68 +0xc79
main.main.func4(0xc00009a840)
        github.com/mikoto2000/devcontainer.vim/main.go:218 +0x251
github.com/urfave/cli/v2.(*Command).Run(0xc0001be2c0, 0xc00009a840, {0xc00007ebc0, 0x2, 0x2})
        github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x97d
github.com/urfave/cli/v2.(*Command).Run(0xc0001be840, 0xc00009a680, {0xc000016120, 0x3, 0x3})
        github.com/urfave/cli/v2@v2.27.1/command.go:272 +0xbb7
github.com/urfave/cli/v2.(*App).RunContext(0xc0001bc000, {0x89d020, 0xb74aa0}, {0xc000016120, 0x3, 0x3})
        github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x58b
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
        github.com/mikoto2000/devcontainer.vim/main.go:319 +0x8dc
```

**Comment by mikoto2000** [comment]
f5888e1b5630f5d55b516eb3047add64cb938999 で対応。
